export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";

// auth:
export const APP_SOCKET_ESTABLISH_CONNECTION =
  "APP_SOCKET_ESTABLISH_CONNECTION";
export const APP_SOCKET_CLOSE_CONNECTION = "APP_SOCKET_CLOSE_CONNECTION";
export const SET_USER_ROLE = "SET_USER_ROLE";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";
export const SET_CURRENT_DEVICE = "SET_CURRENT_DEVICE";
export const USER_LOADING = "USER_LOADING";
export const LOGIN_UNSUCCESSFUL = "LOGIN_UNSUCCESSFUL";
export const REMOVE_LOGIN_ERROR = "REMOVE_LOGIN_ERROR";
export const SET_PASSWORD_START = "SET_PASSWORD_START";
export const SET_PASSWORD_SUCCESS = "SET_PASSWORD_SUCCESS";
export const SET_PASSWORD_FAIL = "SET_PASSWORD_FAIL";
export const CHANGE_PASSWORD_START = "CHANGE_PASSWORD_START";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";
export const CHANGE_PASSWORD_RESET = "CHANGE_PASSWORD_RESET";
export const GET_PROFILE_ONLINE_STATUS_START =
  "GET_PROFILE_ONLINE_STATUS_START";
export const GET_PROFILE_ONLINE_STATUS_SUCCESS =
  "GET_PROFILE_ONLINE_STATUS_SUCCESS";
export const GET_PROFILE_ONLINE_STATUS_FAIL = "GET_PROFILE_ONLINE_STATUS_FAIL";
export const GET_PROFILE_ONLINE_STATUS_RESET =
  "GET_PROFILE_ONLINE_STATUS_RESET";
export const UPDATE_PROFILE_ONLINE_STATUS_START =
  "UPDATE_PROFILE_ONLINE_STATUS_START";
export const UPDATE_PROFILE_ONLINE_STATUS_SUCCESS =
  "UPDATE_PROFILE_ONLINE_STATUS_SUCCESS";
export const UPDATE_PROFILE_ONLINE_STATUS_FAIL =
  "UPDATE_PROFILE_ONLINE_STATUS_FAIL";
export const UPDATE_PROFILE_ONLINE_STATUS_RESET =
  "UPDATE_PROFILE_ONLINE_STATUS_RESET";
export const FORGOT_PASSWORD_START = "FORGOT_PASSWORD_START";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";
export const FORGOT_PASSWORD_RESET = "FORGOT_PASSWORD_RESET";
export const RESET_PASSWORD_START = "RESET_PASSWORD_START";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
export const RESET_PASSWORD_RESET = "RESET_PASSWORD_RESET";

// Auth:
// register:
export const UPDATE_SIGNUP_DATA = "UPDATE_SIGNUP_DATA";
export const SIGNUP_USER_REQUEST = "SIGNUP_USER_REQUEST";
export const SUBMIT_SIGNUP = "SUBMIT_SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
// login:
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
