export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";

// UI:
export const SET_DOCUMENT_DRAGGED_OVER = "SET_DOCUMENT_DRAGGED_OVER";
export const SET_APP_TOUCHED = "SET_APP_TOUCHED";

// sso:
export const GET_SSO_OIDC_ENABLED_REQUEST = "GET_SSO_OIDC_ENABLED_REQUEST";
export const GET_SSO_OIDC_ENABLED_SUCCESS = "GET_SSO_OIDC_ENABLED_SUCCESS";
export const GET_SSO_OIDC_ENABLED_ERROR = "GET_SSO_OIDC_ENABLED_ERROR";

// Auth:
// register:
export const UPDATE_SIGNUP_DATA = "UPDATE_SIGNUP_DATA";
export const SIGNUP_USER_REQUEST = "SIGNUP_USER_REQUEST";
export const SUBMIT_SIGNUP = "SUBMIT_SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
// login:
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
// forgot password:
export const UPDATE_FORGOT_PASSWORD_DATA = "UPDATE_FORGOT_PASSWORD_DATA";
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";
